// <auto-generated />
using HobbyApi.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HobbyApi.Migrations
{
    [DbContext(typeof(HobbyContext))]
    [Migration("20240613123727_HobbyAPIDBMigration")]
    partial class HobbyAPIDBMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("HobbyApi.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Arts & Crafts",
                            Description = "The practice of applying paint, pigment, color, or other medium to a solid surface (such as canvas, paper, or wall) to create expressive or realistic works of art.",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Outdoor Activities",
                            Description = "The practice of growing and cultivating plants as part of horticulture, which can include flowers, vegetables, fruits, and herbs.",
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Education & Learning",
                            Description = "The activity of comprehending written texts, which can range from novels and poetry to non-fiction books and articles, for enjoyment or knowledge.",
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Outdoor Activities",
                            Description = "The activity of going for long walks in the countryside or wilderness, often on trails or footpaths, for exercise and enjoyment of nature.",
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Culinary Arts",
                            Description = "The practice of preparing food by combining, mixing, and heating ingredients to create meals, often exploring different cuisines and techniques.",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Arts & Crafts",
                            Description = "The art or practice of taking and processing photographs, capturing moments, scenes, or subjects using a camera.",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Arts & Crafts",
                            Description = "The craft of creating fabric by interlocking loops of yarn with needles, often to make clothing, accessories, or home decor items.",
                            Name = "Knitting"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Outdoor Activities",
                            Description = "The recreational activity of observing birds in their natural habitat, identifying different species, and noting their behaviors.",
                            Name = "Bird Watching"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Music & Performing Arts",
                            Description = "The activity of playing the guitar, a string instrument, which can involve learning chords, melodies, and songs, and playing various styles of music.",
                            Name = "Playing Guitar"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Health & Fitness",
                            Description = "A group of physical, mental, and spiritual practices or disciplines that aim to improve flexibility, strength, and relaxation through various postures, breathing techniques, and meditation.",
                            Name = "Yoga"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
